name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Run bash-environment-manager      
      run: |
        mkdir -p .repo
        curl https://raw.githubusercontent.com/terminal-labs/bash-environment-shelf/main/prepscripts/mock_vagrant.sh --output .repo/mock_vagrant.sh
        sudo bash .repo/mock_vagrant.sh
        cd /vagrant; sudo su vagrant -c "sudo make psf"
